In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

In [ ]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [ ]:
ROOT_DIR = '/content/gdrive/My Drive/Colab Notebooks'
data_dir = os.path.join(ROOT_DIR, 'original_data')

processed_data_dir = os.path.join(ROOT_DIR, 'preprocessed_data')
os.makedirs(processed_data_dir, exist_ok=True)

In [ ]:
residential_ids = [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 18, 19, 20]
cols_to_process = ['energy_kWh']

In [ ]:
for residential_id in residential_ids:
    data_file = os.path.join(data_dir, 'Residential_{}.csv'.format(residential_id))
    residential_df = pd.read_csv(data_file, 
                          parse_dates={'datetime':['date','hour']}, 
                          infer_datetime_format=True, 
                          index_col='datetime', 
                          low_memory=False)
    
    for col in cols_to_process:
        residential_df[col] = residential_df[col].fillna(residential_df[col].mean())

    processed_data_file = os.path.join(processed_data_dir, 'preprocessed_station_{}.csv'.format(residential_id))
    residential_df.to_csv(processed_data_file)

In [ ]:
for residential_id in residential_ids:

    processed_data_file = os.path.join(processed_data_dir, 'preprocessed_station_{}.csv'.format(residential_id))
    residential_df = pd.read_csv(processed_data_file, 
                          parse_dates=['datetime'], 
                          infer_datetime_format=True, 
                          index_col='datetime', 
                          low_memory=False)
    
    print('id: ', residential_id)
    print(residential_df.info())
    print(residential_df.isnull().sum())
    print()

id:  3
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 26376 entries, 2015-01-27 00:00:00 to 2018-01-29 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  26376 non-null  float64
dtypes: float64(1)
memory usage: 412.1 KB
None
energy_kWh    0
dtype: int64

id:  4
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 26304 entries, 2015-01-30 00:00:00 to 2018-01-29 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  26304 non-null  float64
dtypes: float64(1)
memory usage: 411.0 KB
None
energy_kWh    0
dtype: int64

id:  5
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 26304 entries, 2015-01-30 00:00:00 to 2018-01-29 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  26304 non-null  float64
dtypes: float64(1)
memory usage: 411.0 KB
None
energy_kWh    0
dtype: int64

id:  6
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 26304 entries, 2015-01-30 00:00:00 to 2018-01-29 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  26304 non-null  float64
dtypes: float64(1)
memory usage: 411.0 KB
None
energy_kWh    0
dtype: int64

id:  7
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 23425 entries, 2015-05-30 00:00:00 to 2018-01-29 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  23425 non-null  float64
dtypes: float64(1)
memory usage: 366.0 KB
None
energy_kWh    0
dtype: int64

id:  8
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 26304 entries, 2015-02-21 00:00:00 to 2018-02-20 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  26304 non-null  float64
dtypes: float64(1)
memory usage: 411.0 KB
None
energy_kWh    0
dtype: int64

id:  9
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 24673 entries, 2015-05-01 00:00:00 to 2018-02-21 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  24673 non-null  float64
dtypes: float64(1)
memory usage: 385.5 KB
None
energy_kWh    0
dtype: int64

id:  10
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 26304 entries, 2015-02-21 00:00:00 to 2018-02-20 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  26304 non-null  float64
dtypes: float64(1)
memory usage: 411.0 KB
None
energy_kWh    0
dtype: int64

id:  11
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 26304 entries, 2015-02-21 00:00:00 to 2018-02-20 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  26304 non-null  float64
dtypes: float64(1)
memory usage: 411.0 KB
None
energy_kWh    0
dtype: int64

id:  12
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 26304 entries, 2015-02-21 00:00:00 to 2018-02-20 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  26304 non-null  float64
dtypes: float64(1)
memory usage: 411.0 KB
None
energy_kWh    0
dtype: int64

id:  13
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 26304 entries, 2015-02-21 00:00:00 to 2018-02-20 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  26304 non-null  float64
dtypes: float64(1)
memory usage: 411.0 KB
None
energy_kWh    0
dtype: int64

id:  14
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 26304 entries, 2015-02-21 00:00:00 to 2018-02-20 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  26304 non-null  float64
dtypes: float64(1)
memory usage: 411.0 KB
None
energy_kWh    0
dtype: int64

id:  15
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 21025 entries, 2015-09-29 00:00:00 to 2018-02-20 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  21025 non-null  float64
dtypes: float64(1)
memory usage: 328.5 KB
None
energy_kWh    0
dtype: int64

id:  18
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 26304 entries, 2015-03-16 00:00:00 to 2018-03-15 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  26304 non-null  float64
dtypes: float64(1)
memory usage: 411.0 KB
None
energy_kWh    0
dtype: int64

id:  19
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 26304 entries, 2015-03-26 00:00:00 to 2018-03-25 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  26304 non-null  float64
dtypes: float64(1)
memory usage: 411.0 KB
None
energy_kWh    0
dtype: int64

id:  20
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 23376 entries, 2015-08-21 00:00:00 to 2018-04-20 23:00:00
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   energy_kWh  23376 non-null  float64
dtypes: float64(1)
memory usage: 365.2 KB
None
energy_kWh    0
dtype: int64